Completed issues #42 and #44. Completed L1 support for issue #43; I still need to build L2 support for issue #43.
All Java tests pass.
All Avail tests pass.

[VM]
- L2_GET_INVALID_MESSAGE_SEND_FUNCTION,
L2_GET_UNASSIGNED_VARIABLE_READ_FUNCTION: New L2 instructions.
- L2_REPORT_FAILED_LOOKUP => L2_DIAGNOSE_LOOKUP_FAILURE: Changed the
semantics completely.
- L2_GET_VARIABLE, L2_GET_VARIABLE_CLEARING, L2_LOOKUP_BY_VALUES: Now
accept a PC to branch to in the event of success.
- P_075 … P_078: Now provide sensible names for their argument functions
(to assist in reading stack traces).
- Interpreter: Fixes related to issue #43.
- ForwardDefinitionDescriptor: Forward definitions now print correctly.
- L1Decompiler: Removed bogus code.
- L1InstructionStepper: Fixes related to issues #42 and #44.
- L2Translator: L1 off-ramps are now generated for failed variable reads
and invalid message sends.
- RenamesFileParser: I broke this completely when I updated it for
Unicode. It now works again.

/distro/bin:
avail-dev: Now correctly passes AVAIL_RENAMES to Java.

diff --git a/Avail/distro/bin/avail-dev b/Avail/distro/bin/avail-dev
--- a/Avail/distro/bin/avail-dev
+++ b/Avail/distro/bin/avail-dev
@@ -59,6 +59,15 @@ elif [ ! -f $CONFIG/logging.properties ]; then
 	exit 1
 fi
 
+# Create an empty renames file, but only if the user does not already have an
+# existing one.
+if [ ! -e $CONFIG/renames ]; then
+	touch $CONFIG/renames
+elif [ ! -f $CONFIG/renames ]; then
+	echo "Fatal error: $CONFIG/renames exists but it is not a regular file"
+	exit 1
+fi
+
 # Create the repository directory if necessary. Fix the permissions if it is
 # not readable and writable by the current user.
 REPOS=$AVAIL_USER/repos
@@ -74,6 +83,11 @@ fi
 # If AVAIL_ROOTS is not set, then default it.
 if [ "X$AVAIL_ROOTS" = "X" ]; then
 	AVAIL_ROOTS="avail=$REPOS/avail.repo,$AVAIL_HOME/src/avail"';'"examples=$REPOS/examples.repo,$AVAIL_HOME/src/examples"
+fi
+
+# If AVAIL_RENAMES is not set, then default it.
+if [ "X$AVAIL_RENAMES" = "X" ]; then
+	AVAIL_RENAMES="$CONFIG/renames"
 fi
 
 # Find the Java virtual machine.
@@ -92,7 +106,7 @@ else
 fi
 
 # These are the system arguments for the Java virtual machine.
-VMARGS=-classpath\ "$AVAIL_HOME/lib"\ $OSARGS\ -XX:-UseSplitVerifier\ "-Djava.util.logging.config.file=$HOME/.avail/logging.properties"\ "-DavailRoots=$AVAIL_ROOTS"
+VMARGS=-classpath\ "$AVAIL_HOME/lib"\ $OSARGS\ -XX:-UseSplitVerifier\ "-Djava.util.logging.config.file=$HOME/.avail/logging.properties"\ "-DavailRoots=$AVAIL_ROOTS"\ "-DavailRenames=$AVAIL_RENAMES"
 
 # Launch the Avail development environment in the background.
 DEVJAR=$AVAIL_HOME/lib/AvailDev.jar
